### ISSUE TITLE
JsonToObjectConverterOptions constants

### ISSUE THREAD

**Issue by IIeTp** [starnutoditopo/JsonToObject#1]
Hi, is this possible to not use these consts, but make standart output?
![image](https://github.com/starnutoditopo/JsonToObject/assets/52212265/cea74e17-443e-4cd0-af0c-095391a3437c)

**Comment by starnutoditopo** [comment]
Sorry: I don't really understand your question.

**Comment by IIeTp** [comment]
> Sorry: I don't really understand your question.

i mean, maybe there is a way to not use default consts, like this `{RuntimeGeneratedType_{0}}`
![image](https://github.com/starnutoditopo/JsonToObject/assets/52212265/4779ca71-6fef-4c22-ac66-04e1dc8465ac)

and use standart type output, like this
![image](https://github.com/starnutoditopo/JsonToObject/assets/52212265/6f8ba354-8f6a-4714-bce4-61d546a6d3f4)

second screenshot is mine code, but i'd like to take best of both, like your structure and save information about count of vars inside object

**Comment by IIeTp** [comment]
okay, probably it's impossible

**Comment by starnutoditopo** [comment]
Well... maybe the runtime-generated types may be marked with some
customizable string in a [DebuggerDisplay] attribute...

**Comment by StefanoOcchetti** [comment]
Have a look at the branch:

https://github.com/starnutoditopo/JsonToObject/tree/feature/Add-DebuggerDisplayAttribute

I also added this example:

public void CustomizedDebuggerDisplayName()

I didn't apply this change to the main branch directly, because maybe a more general feature could be implemented, to add any attribute when a type is generated.
